name: OWASP ZAP DAST Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start the backend service
        run: |
          docker build -t backend ./backend
          docker run -d -p 3000:3000 --name backend backend
          sleep 10  # give the server time to start

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --network="host" ghcr.io/zaproxy/zaproxy zap-baseline.py -t http://localhost:3000 -r zap-report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap-report.html
          
