name: DAST Scan with OWASP ZAP

on:
  push:
    branches: [main]
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run OWASP ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.10.0
      with:
        target: 'http://your-backend-url:3000'  # CHANGE THIS to your actual public or test env URL
        docker_name: 'ghcr.io/zaproxy/zaproxy'
        cmd_options: '-t 60 -r zap-report.html'

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: zap-report
        path: zap-report.html
